Repository ssumday24/pintos_week12, pull requests merged in 2025-08, with the labels that each got.

#16 lazy_load_segment, load_segment 구현
  pintos/tests/Make.tests
  pintos/userprog/process.c
  pintos/utils/backtrace
  pintos/utils/pintos
  pintos/utils/pintos-mkdisk
Labels: good first issue

#23 Fix
  pintos/userprog/syscall.c
Labels: bug

#26 feat : `spt_kill` , `uninit_destroy`
  pintos/vm/uninit.c
  pintos/vm/vm.c
Labels: enhancement

#33 Feat
  pintos/include/threads/thread.h
  pintos/threads/thread.c
  pintos/userprog/syscall.c
  pintos/vm/vm.c
Labels: enhancement

#42 Feat Clock Algorithm
  pintos/include/vm/vm.h
  pintos/vm/vm.c
Labels: enhancement
